#!/bin/bash
# cleanup.sh — Remove generated/temporary files from the NeuroSim directory.
#
# Safe to remove:
#   - layer_record_*/         (PPA trace dirs, regenerated each run)
#   - NeuroSIM/NetWork_*.csv  (generated network files, NOT the original vgg8)
#   - __pycache__/            (Python bytecode cache)
#   - sweep_config_type*.json (generated by split_config.py)
#
# NOT removed:
#   - results/                (your .pt files and plots!)
#   - *.py                    (source code)
#   - mem_states_*.csv        (device config files)
#   - sweep_config.json       (main config)
#   - sweep_config_quick.json (quick test config)
#   - NeuroSIM/main           (compiled binary)
#   - NeuroSIM/NetWork_vgg8.csv (original NeuroSim file)
#
# Usage:
#   bash cleanup.sh           (dry run — shows what would be deleted)
#   bash cleanup.sh --delete  (actually delete)

DRY_RUN=true
if [ "$1" = "--delete" ]; then
    DRY_RUN=false
fi

echo "=== Cleanup ==="
echo ""

# PPA trace directories
TRACE_DIRS=$(find . -maxdepth 1 -name "layer_record_*" -type d 2>/dev/null)
if [ -n "$TRACE_DIRS" ]; then
    echo "PPA trace directories:"
    for d in $TRACE_DIRS; do
        SIZE=$(du -sh "$d" 2>/dev/null | cut -f1)
        echo "  $d ($SIZE)"
    done
    if [ "$DRY_RUN" = false ]; then
        rm -rf layer_record_*/
        echo "  → Deleted"
    fi
    echo ""
fi

# Generated NetWork CSVs (only delete our exp/test files, keep all originals)
GEN_CSV=$(find ./NeuroSIM -maxdepth 1 -name "NetWork_exp12_*.csv" -o -name "NetWork_ppa_*.csv" -o -name "NetWork_avg_*.csv" -o -name "NetWork_tile_*.csv" 2>/dev/null)
if [ -n "$GEN_CSV" ]; then
    echo "Generated NetWork CSVs:"
    for f in $GEN_CSV; do
        echo "  $f"
    done
    if [ "$DRY_RUN" = false ]; then
        find ./NeuroSIM -maxdepth 1 \( -name "NetWork_exp12_*.csv" -o -name "NetWork_ppa_*.csv" -o -name "NetWork_avg_*.csv" -o -name "NetWork_tile_*.csv" \) -delete
        echo "  → Deleted"
    fi
    echo ""
fi

# Python cache
PYCACHE=$(find . -name "__pycache__" -type d 2>/dev/null)
if [ -n "$PYCACHE" ]; then
    echo "Python cache directories:"
    for d in $PYCACHE; do
        echo "  $d"
    done
    if [ "$DRY_RUN" = false ]; then
        find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null
        echo "  → Deleted"
    fi
    echo ""
fi

# Split config files
SPLIT_CFG=$(find . -maxdepth 1 -name "sweep_config_type*.json" 2>/dev/null)
if [ -n "$SPLIT_CFG" ]; then
    echo "Split config files:"
    for f in $SPLIT_CFG; do
        echo "  $f"
    done
    if [ "$DRY_RUN" = false ]; then
        rm -f sweep_config_type*.json
        echo "  → Deleted"
    fi
    echo ""
fi

# Summary
if [ "$DRY_RUN" = true ]; then
    echo "=== Dry run — nothing deleted ==="
    echo "Run 'bash cleanup.sh --delete' to actually delete"
else
    echo "=== Cleanup complete ==="
fi

# Show what's preserved
echo ""
echo "Preserved:"
echo "  results/               (your data!)"
echo "  *.py                   (source code)"
echo "  sweep_config*.json     (configs, except split files)"
echo "  mem_states_*.csv       (device params)"
echo "  NeuroSIM/main          (compiled binary)"
